#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqChengQuDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertChengQu(ChengQu instance);
  partial void UpdateChengQu(ChengQu instance);
  partial void DeleteChengQu(ChengQu instance);
  #endregion
	
	public linqChengQuDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqChengQuDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqChengQuDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqChengQuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqChengQuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ChengQu> ChengQu
	{
		get
		{
			return this.GetTable<ChengQu>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChengQu")]
public partial class ChengQu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Cq_Id;
	
	private string _Cq_Name;
	
	private string _Cq_Gmaps;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCq_IdChanging(int value);
    partial void OnCq_IdChanged();
    partial void OnCq_NameChanging(string value);
    partial void OnCq_NameChanged();
    partial void OnCq_GmapsChanging(string value);
    partial void OnCq_GmapsChanged();
    #endregion
	
	public ChengQu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cq_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Cq_Id
	{
		get
		{
			return this._Cq_Id;
		}
		set
		{
			if ((this._Cq_Id != value))
			{
				this.OnCq_IdChanging(value);
				this.SendPropertyChanging();
				this._Cq_Id = value;
				this.SendPropertyChanged("Cq_Id");
				this.OnCq_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cq_Name", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Cq_Name
	{
		get
		{
			return this._Cq_Name;
		}
		set
		{
			if ((this._Cq_Name != value))
			{
				this.OnCq_NameChanging(value);
				this.SendPropertyChanging();
				this._Cq_Name = value;
				this.SendPropertyChanged("Cq_Name");
				this.OnCq_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cq_Gmaps", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Cq_Gmaps
	{
		get
		{
			return this._Cq_Gmaps;
		}
		set
		{
			if ((this._Cq_Gmaps != value))
			{
				this.OnCq_GmapsChanging(value);
				this.SendPropertyChanging();
				this._Cq_Gmaps = value;
				this.SendPropertyChanged("Cq_Gmaps");
				this.OnCq_GmapsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
