#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqShangQuanDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertShangQuan(ShangQuan instance);
  partial void UpdateShangQuan(ShangQuan instance);
  partial void DeleteShangQuan(ShangQuan instance);
  #endregion
	
	public linqShangQuanDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqShangQuanDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqShangQuanDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqShangQuanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqShangQuanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ShangQuan> ShangQuan
	{
		get
		{
			return this.GetTable<ShangQuan>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShangQuan")]
public partial class ShangQuan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Sq_Id;
	
	private string _Sq_Name;
	
	private string _Sq_Gmaps;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSq_IdChanging(int value);
    partial void OnSq_IdChanged();
    partial void OnSq_NameChanging(string value);
    partial void OnSq_NameChanged();
    partial void OnSq_GmapsChanging(string value);
    partial void OnSq_GmapsChanged();
    #endregion
	
	public ShangQuan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sq_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Sq_Id
	{
		get
		{
			return this._Sq_Id;
		}
		set
		{
			if ((this._Sq_Id != value))
			{
				this.OnSq_IdChanging(value);
				this.SendPropertyChanging();
				this._Sq_Id = value;
				this.SendPropertyChanged("Sq_Id");
				this.OnSq_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sq_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Sq_Name
	{
		get
		{
			return this._Sq_Name;
		}
		set
		{
			if ((this._Sq_Name != value))
			{
				this.OnSq_NameChanging(value);
				this.SendPropertyChanging();
				this._Sq_Name = value;
				this.SendPropertyChanged("Sq_Name");
				this.OnSq_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sq_Gmaps", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Sq_Gmaps
	{
		get
		{
			return this._Sq_Gmaps;
		}
		set
		{
			if ((this._Sq_Gmaps != value))
			{
				this.OnSq_GmapsChanging(value);
				this.SendPropertyChanging();
				this._Sq_Gmaps = value;
				this.SendPropertyChanged("Sq_Gmaps");
				this.OnSq_GmapsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
