#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqKeHuDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertKeHu(KeHu instance);
  partial void UpdateKeHu(KeHu instance);
  partial void DeleteKeHu(KeHu instance);
  #endregion
	
	public linqKeHuDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqKeHuDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqKeHuDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqKeHuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqKeHuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<KeHu> KeHu
	{
		get
		{
			return this.GetTable<KeHu>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KeHu")]
public partial class KeHu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Kh_Id;
	
	private string _Kh_XingMing;
	
	private string _Kh_XingBie;
	
	private string _Kh_DianHua;
	
	private string _Kh_JingJiRen;
	
	private int _Kh_JingJiRenId;
	
	private string _Kh_MenDian;
	
	private int _Kh_MenDianId;
	
	private string _Kh_ShenFenZheng;
	
	private string _Kh_BeiZhu;
	
	private System.DateTime _Kh_TianJiaShiJian;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKh_IdChanging(int value);
    partial void OnKh_IdChanged();
    partial void OnKh_XingMingChanging(string value);
    partial void OnKh_XingMingChanged();
    partial void OnKh_XingBieChanging(string value);
    partial void OnKh_XingBieChanged();
    partial void OnKh_DianHuaChanging(string value);
    partial void OnKh_DianHuaChanged();
    partial void OnKh_JingJiRenChanging(string value);
    partial void OnKh_JingJiRenChanged();
    partial void OnKh_JingJiRenIdChanging(int value);
    partial void OnKh_JingJiRenIdChanged();
    partial void OnKh_MenDianChanging(string value);
    partial void OnKh_MenDianChanged();
    partial void OnKh_MenDianIdChanging(int value);
    partial void OnKh_MenDianIdChanged();
    partial void OnKh_ShenFenZhengChanging(string value);
    partial void OnKh_ShenFenZhengChanged();
    partial void OnKh_BeiZhuChanging(string value);
    partial void OnKh_BeiZhuChanged();
    partial void OnKh_TianJiaShiJianChanging(System.DateTime value);
    partial void OnKh_TianJiaShiJianChanged();
    #endregion
	
	public KeHu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Kh_Id
	{
		get
		{
			return this._Kh_Id;
		}
		set
		{
			if ((this._Kh_Id != value))
			{
				this.OnKh_IdChanging(value);
				this.SendPropertyChanging();
				this._Kh_Id = value;
				this.SendPropertyChanged("Kh_Id");
				this.OnKh_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_XingMing", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Kh_XingMing
	{
		get
		{
			return this._Kh_XingMing;
		}
		set
		{
			if ((this._Kh_XingMing != value))
			{
				this.OnKh_XingMingChanging(value);
				this.SendPropertyChanging();
				this._Kh_XingMing = value;
				this.SendPropertyChanged("Kh_XingMing");
				this.OnKh_XingMingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_XingBie", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string Kh_XingBie
	{
		get
		{
			return this._Kh_XingBie;
		}
		set
		{
			if ((this._Kh_XingBie != value))
			{
				this.OnKh_XingBieChanging(value);
				this.SendPropertyChanging();
				this._Kh_XingBie = value;
				this.SendPropertyChanged("Kh_XingBie");
				this.OnKh_XingBieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_DianHua", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Kh_DianHua
	{
		get
		{
			return this._Kh_DianHua;
		}
		set
		{
			if ((this._Kh_DianHua != value))
			{
				this.OnKh_DianHuaChanging(value);
				this.SendPropertyChanging();
				this._Kh_DianHua = value;
				this.SendPropertyChanged("Kh_DianHua");
				this.OnKh_DianHuaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_JingJiRen", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Kh_JingJiRen
	{
		get
		{
			return this._Kh_JingJiRen;
		}
		set
		{
			if ((this._Kh_JingJiRen != value))
			{
				this.OnKh_JingJiRenChanging(value);
				this.SendPropertyChanging();
				this._Kh_JingJiRen = value;
				this.SendPropertyChanged("Kh_JingJiRen");
				this.OnKh_JingJiRenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_JingJiRenId", DbType="Int NOT NULL")]
	public int Kh_JingJiRenId
	{
		get
		{
			return this._Kh_JingJiRenId;
		}
		set
		{
			if ((this._Kh_JingJiRenId != value))
			{
				this.OnKh_JingJiRenIdChanging(value);
				this.SendPropertyChanging();
				this._Kh_JingJiRenId = value;
				this.SendPropertyChanged("Kh_JingJiRenId");
				this.OnKh_JingJiRenIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_MenDian", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Kh_MenDian
	{
		get
		{
			return this._Kh_MenDian;
		}
		set
		{
			if ((this._Kh_MenDian != value))
			{
				this.OnKh_MenDianChanging(value);
				this.SendPropertyChanging();
				this._Kh_MenDian = value;
				this.SendPropertyChanged("Kh_MenDian");
				this.OnKh_MenDianChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_MenDianId", DbType="Int NOT NULL")]
	public int Kh_MenDianId
	{
		get
		{
			return this._Kh_MenDianId;
		}
		set
		{
			if ((this._Kh_MenDianId != value))
			{
				this.OnKh_MenDianIdChanging(value);
				this.SendPropertyChanging();
				this._Kh_MenDianId = value;
				this.SendPropertyChanged("Kh_MenDianId");
				this.OnKh_MenDianIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_ShenFenZheng", DbType="VarChar(30)")]
	public string Kh_ShenFenZheng
	{
		get
		{
			return this._Kh_ShenFenZheng;
		}
		set
		{
			if ((this._Kh_ShenFenZheng != value))
			{
				this.OnKh_ShenFenZhengChanging(value);
				this.SendPropertyChanging();
				this._Kh_ShenFenZheng = value;
				this.SendPropertyChanged("Kh_ShenFenZheng");
				this.OnKh_ShenFenZhengChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_BeiZhu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Kh_BeiZhu
	{
		get
		{
			return this._Kh_BeiZhu;
		}
		set
		{
			if ((this._Kh_BeiZhu != value))
			{
				this.OnKh_BeiZhuChanging(value);
				this.SendPropertyChanging();
				this._Kh_BeiZhu = value;
				this.SendPropertyChanged("Kh_BeiZhu");
				this.OnKh_BeiZhuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kh_TianJiaShiJian", DbType="Date NOT NULL")]
	public System.DateTime Kh_TianJiaShiJian
	{
		get
		{
			return this._Kh_TianJiaShiJian;
		}
		set
		{
			if ((this._Kh_TianJiaShiJian != value))
			{
				this.OnKh_TianJiaShiJianChanging(value);
				this.SendPropertyChanging();
				this._Kh_TianJiaShiJian = value;
				this.SendPropertyChanged("Kh_TianJiaShiJian");
				this.OnKh_TianJiaShiJianChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
