#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqGongGaoDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertGongGao(GongGao instance);
  partial void UpdateGongGao(GongGao instance);
  partial void DeleteGongGao(GongGao instance);
  #endregion
	
	public linqGongGaoDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqGongGaoDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqGongGaoDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqGongGaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqGongGaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<GongGao> GongGao
	{
		get
		{
			return this.GetTable<GongGao>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GongGao")]
public partial class GongGao : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Gg_Id;
	
	private string _Gg_Name;
	
	private string _Gg_NeiRong;
	
	private string _Gg_MenDian;
	
	private int _Gg_MenDianId;
	
	private string _Gg_User;
	
	private int _Gg_UserId;
	
	private System.DateTime _Gg_TianJiaShiJian;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGg_IdChanging(int value);
    partial void OnGg_IdChanged();
    partial void OnGg_NameChanging(string value);
    partial void OnGg_NameChanged();
    partial void OnGg_NeiRongChanging(string value);
    partial void OnGg_NeiRongChanged();
    partial void OnGg_MenDianChanging(string value);
    partial void OnGg_MenDianChanged();
    partial void OnGg_MenDianIdChanging(int value);
    partial void OnGg_MenDianIdChanged();
    partial void OnGg_UserChanging(string value);
    partial void OnGg_UserChanged();
    partial void OnGg_UserIdChanging(int value);
    partial void OnGg_UserIdChanged();
    partial void OnGg_TianJiaShiJianChanging(System.DateTime value);
    partial void OnGg_TianJiaShiJianChanged();
    #endregion
	
	public GongGao()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Gg_Id
	{
		get
		{
			return this._Gg_Id;
		}
		set
		{
			if ((this._Gg_Id != value))
			{
				this.OnGg_IdChanging(value);
				this.SendPropertyChanging();
				this._Gg_Id = value;
				this.SendPropertyChanged("Gg_Id");
				this.OnGg_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Gg_Name
	{
		get
		{
			return this._Gg_Name;
		}
		set
		{
			if ((this._Gg_Name != value))
			{
				this.OnGg_NameChanging(value);
				this.SendPropertyChanging();
				this._Gg_Name = value;
				this.SendPropertyChanged("Gg_Name");
				this.OnGg_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_NeiRong", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Gg_NeiRong
	{
		get
		{
			return this._Gg_NeiRong;
		}
		set
		{
			if ((this._Gg_NeiRong != value))
			{
				this.OnGg_NeiRongChanging(value);
				this.SendPropertyChanging();
				this._Gg_NeiRong = value;
				this.SendPropertyChanged("Gg_NeiRong");
				this.OnGg_NeiRongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_MenDian", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Gg_MenDian
	{
		get
		{
			return this._Gg_MenDian;
		}
		set
		{
			if ((this._Gg_MenDian != value))
			{
				this.OnGg_MenDianChanging(value);
				this.SendPropertyChanging();
				this._Gg_MenDian = value;
				this.SendPropertyChanged("Gg_MenDian");
				this.OnGg_MenDianChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_MenDianId", DbType="Int NOT NULL")]
	public int Gg_MenDianId
	{
		get
		{
			return this._Gg_MenDianId;
		}
		set
		{
			if ((this._Gg_MenDianId != value))
			{
				this.OnGg_MenDianIdChanging(value);
				this.SendPropertyChanging();
				this._Gg_MenDianId = value;
				this.SendPropertyChanged("Gg_MenDianId");
				this.OnGg_MenDianIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_User", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Gg_User
	{
		get
		{
			return this._Gg_User;
		}
		set
		{
			if ((this._Gg_User != value))
			{
				this.OnGg_UserChanging(value);
				this.SendPropertyChanging();
				this._Gg_User = value;
				this.SendPropertyChanged("Gg_User");
				this.OnGg_UserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_UserId", DbType="Int NOT NULL")]
	public int Gg_UserId
	{
		get
		{
			return this._Gg_UserId;
		}
		set
		{
			if ((this._Gg_UserId != value))
			{
				this.OnGg_UserIdChanging(value);
				this.SendPropertyChanging();
				this._Gg_UserId = value;
				this.SendPropertyChanged("Gg_UserId");
				this.OnGg_UserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gg_TianJiaShiJian", DbType="Date NOT NULL")]
	public System.DateTime Gg_TianJiaShiJian
	{
		get
		{
			return this._Gg_TianJiaShiJian;
		}
		set
		{
			if ((this._Gg_TianJiaShiJian != value))
			{
				this.OnGg_TianJiaShiJianChanging(value);
				this.SendPropertyChanging();
				this._Gg_TianJiaShiJian = value;
				this.SendPropertyChanged("Gg_TianJiaShiJian");
				this.OnGg_TianJiaShiJianChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
