#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqJiaoYiDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertJiaoYi(JiaoYi instance);
  partial void UpdateJiaoYi(JiaoYi instance);
  partial void DeleteJiaoYi(JiaoYi instance);
  #endregion
	
	public linqJiaoYiDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqJiaoYiDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqJiaoYiDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqJiaoYiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqJiaoYiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<JiaoYi> JiaoYi
	{
		get
		{
			return this.GetTable<JiaoYi>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JiaoYi")]
public partial class JiaoYi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Jy_Id;
	
	private int _Jy_YuanGongId;
	
	private int _Jy_FangYuanId;
	
	private int _Jy_FangZhuId;
	
	private int _Jy_KeHuId;
	
	private string _Jy_LeiXing;
	
	private int _Jy_JiaGe;
	
	private int _Jy_YongJin;
	
	private int _Jy_TiCheng;
	
	private string _Jy_BeiZhu;
	
	private System.DateTime _Jy_ShiJian;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJy_IdChanging(int value);
    partial void OnJy_IdChanged();
    partial void OnJy_YuanGongIdChanging(int value);
    partial void OnJy_YuanGongIdChanged();
    partial void OnJy_FangYuanIdChanging(int value);
    partial void OnJy_FangYuanIdChanged();
    partial void OnJy_FangZhuIdChanging(int value);
    partial void OnJy_FangZhuIdChanged();
    partial void OnJy_KeHuIdChanging(int value);
    partial void OnJy_KeHuIdChanged();
    partial void OnJy_LeiXingChanging(string value);
    partial void OnJy_LeiXingChanged();
    partial void OnJy_JiaGeChanging(int value);
    partial void OnJy_JiaGeChanged();
    partial void OnJy_YongJinChanging(int value);
    partial void OnJy_YongJinChanged();
    partial void OnJy_TiChengChanging(int value);
    partial void OnJy_TiChengChanged();
    partial void OnJy_BeiZhuChanging(string value);
    partial void OnJy_BeiZhuChanged();
    partial void OnJy_ShiJianChanging(System.DateTime value);
    partial void OnJy_ShiJianChanged();
    #endregion
	
	public JiaoYi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Jy_Id
	{
		get
		{
			return this._Jy_Id;
		}
		set
		{
			if ((this._Jy_Id != value))
			{
				this.OnJy_IdChanging(value);
				this.SendPropertyChanging();
				this._Jy_Id = value;
				this.SendPropertyChanged("Jy_Id");
				this.OnJy_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_YuanGongId", DbType="Int NOT NULL")]
	public int Jy_YuanGongId
	{
		get
		{
			return this._Jy_YuanGongId;
		}
		set
		{
			if ((this._Jy_YuanGongId != value))
			{
				this.OnJy_YuanGongIdChanging(value);
				this.SendPropertyChanging();
				this._Jy_YuanGongId = value;
				this.SendPropertyChanged("Jy_YuanGongId");
				this.OnJy_YuanGongIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_FangYuanId", DbType="Int NOT NULL")]
	public int Jy_FangYuanId
	{
		get
		{
			return this._Jy_FangYuanId;
		}
		set
		{
			if ((this._Jy_FangYuanId != value))
			{
				this.OnJy_FangYuanIdChanging(value);
				this.SendPropertyChanging();
				this._Jy_FangYuanId = value;
				this.SendPropertyChanged("Jy_FangYuanId");
				this.OnJy_FangYuanIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_FangZhuId", DbType="Int NOT NULL")]
	public int Jy_FangZhuId
	{
		get
		{
			return this._Jy_FangZhuId;
		}
		set
		{
			if ((this._Jy_FangZhuId != value))
			{
				this.OnJy_FangZhuIdChanging(value);
				this.SendPropertyChanging();
				this._Jy_FangZhuId = value;
				this.SendPropertyChanged("Jy_FangZhuId");
				this.OnJy_FangZhuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_KeHuId", DbType="Int NOT NULL")]
	public int Jy_KeHuId
	{
		get
		{
			return this._Jy_KeHuId;
		}
		set
		{
			if ((this._Jy_KeHuId != value))
			{
				this.OnJy_KeHuIdChanging(value);
				this.SendPropertyChanging();
				this._Jy_KeHuId = value;
				this.SendPropertyChanged("Jy_KeHuId");
				this.OnJy_KeHuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_LeiXing", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Jy_LeiXing
	{
		get
		{
			return this._Jy_LeiXing;
		}
		set
		{
			if ((this._Jy_LeiXing != value))
			{
				this.OnJy_LeiXingChanging(value);
				this.SendPropertyChanging();
				this._Jy_LeiXing = value;
				this.SendPropertyChanged("Jy_LeiXing");
				this.OnJy_LeiXingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_JiaGe", DbType="Int NOT NULL")]
	public int Jy_JiaGe
	{
		get
		{
			return this._Jy_JiaGe;
		}
		set
		{
			if ((this._Jy_JiaGe != value))
			{
				this.OnJy_JiaGeChanging(value);
				this.SendPropertyChanging();
				this._Jy_JiaGe = value;
				this.SendPropertyChanged("Jy_JiaGe");
				this.OnJy_JiaGeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_YongJin", DbType="Int NOT NULL")]
	public int Jy_YongJin
	{
		get
		{
			return this._Jy_YongJin;
		}
		set
		{
			if ((this._Jy_YongJin != value))
			{
				this.OnJy_YongJinChanging(value);
				this.SendPropertyChanging();
				this._Jy_YongJin = value;
				this.SendPropertyChanged("Jy_YongJin");
				this.OnJy_YongJinChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_TiCheng", DbType="Int NOT NULL")]
	public int Jy_TiCheng
	{
		get
		{
			return this._Jy_TiCheng;
		}
		set
		{
			if ((this._Jy_TiCheng != value))
			{
				this.OnJy_TiChengChanging(value);
				this.SendPropertyChanging();
				this._Jy_TiCheng = value;
				this.SendPropertyChanged("Jy_TiCheng");
				this.OnJy_TiChengChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_BeiZhu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Jy_BeiZhu
	{
		get
		{
			return this._Jy_BeiZhu;
		}
		set
		{
			if ((this._Jy_BeiZhu != value))
			{
				this.OnJy_BeiZhuChanging(value);
				this.SendPropertyChanging();
				this._Jy_BeiZhu = value;
				this.SendPropertyChanged("Jy_BeiZhu");
				this.OnJy_BeiZhuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jy_ShiJian", DbType="Date NOT NULL")]
	public System.DateTime Jy_ShiJian
	{
		get
		{
			return this._Jy_ShiJian;
		}
		set
		{
			if ((this._Jy_ShiJian != value))
			{
				this.OnJy_ShiJianChanging(value);
				this.SendPropertyChanging();
				this._Jy_ShiJian = value;
				this.SendPropertyChanged("Jy_ShiJian");
				this.OnJy_ShiJianChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
