#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqYuanGongDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertYuanGong(YuanGong instance);
  partial void UpdateYuanGong(YuanGong instance);
  partial void DeleteYuanGong(YuanGong instance);
  #endregion
	
	public linqYuanGongDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqYuanGongDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYuanGongDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYuanGongDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYuanGongDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<YuanGong> YuanGong
	{
		get
		{
			return this.GetTable<YuanGong>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YuanGong")]
public partial class YuanGong : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Yg_Id;
	
	private string _Yg_Name;
	
	private string _Yg_Pwd;
	
	private string _Yg_XingMing;
	
	private string _Yg_MenDian;
	
	private int _Yg_MenDianId;
	
	private string _Yg_XingBie;
	
	private string _Yg_DianHua;
	
	private int _Yg_ZhuangTai;
	
	private int _Yg_JiBie;
	
	private string _Yg_ShenFen;
	
	private string _Yg_XueLi;
	
	private int _Yg_NianLing;
	
	private System.DateTime _Yg_RuZhi;
	
	private string _Yg_ZhuZhi;
	
	private string _Yg_BeiZhu;
	
	private System.DateTime _Yg_TianJia;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYg_IdChanging(int value);
    partial void OnYg_IdChanged();
    partial void OnYg_NameChanging(string value);
    partial void OnYg_NameChanged();
    partial void OnYg_PwdChanging(string value);
    partial void OnYg_PwdChanged();
    partial void OnYg_XingMingChanging(string value);
    partial void OnYg_XingMingChanged();
    partial void OnYg_MenDianChanging(string value);
    partial void OnYg_MenDianChanged();
    partial void OnYg_MenDianIdChanging(int value);
    partial void OnYg_MenDianIdChanged();
    partial void OnYg_XingBieChanging(string value);
    partial void OnYg_XingBieChanged();
    partial void OnYg_DianHuaChanging(string value);
    partial void OnYg_DianHuaChanged();
    partial void OnYg_ZhuangTaiChanging(int value);
    partial void OnYg_ZhuangTaiChanged();
    partial void OnYg_JiBieChanging(int value);
    partial void OnYg_JiBieChanged();
    partial void OnYg_ShenFenChanging(string value);
    partial void OnYg_ShenFenChanged();
    partial void OnYg_XueLiChanging(string value);
    partial void OnYg_XueLiChanged();
    partial void OnYg_NianLingChanging(int value);
    partial void OnYg_NianLingChanged();
    partial void OnYg_RuZhiChanging(System.DateTime value);
    partial void OnYg_RuZhiChanged();
    partial void OnYg_ZhuZhiChanging(string value);
    partial void OnYg_ZhuZhiChanged();
    partial void OnYg_BeiZhuChanging(string value);
    partial void OnYg_BeiZhuChanged();
    partial void OnYg_TianJiaChanging(System.DateTime value);
    partial void OnYg_TianJiaChanged();
    #endregion
	
	public YuanGong()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Yg_Id
	{
		get
		{
			return this._Yg_Id;
		}
		set
		{
			if ((this._Yg_Id != value))
			{
				this.OnYg_IdChanging(value);
				this.SendPropertyChanging();
				this._Yg_Id = value;
				this.SendPropertyChanged("Yg_Id");
				this.OnYg_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_Name", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_Name
	{
		get
		{
			return this._Yg_Name;
		}
		set
		{
			if ((this._Yg_Name != value))
			{
				this.OnYg_NameChanging(value);
				this.SendPropertyChanging();
				this._Yg_Name = value;
				this.SendPropertyChanged("Yg_Name");
				this.OnYg_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_Pwd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_Pwd
	{
		get
		{
			return this._Yg_Pwd;
		}
		set
		{
			if ((this._Yg_Pwd != value))
			{
				this.OnYg_PwdChanging(value);
				this.SendPropertyChanging();
				this._Yg_Pwd = value;
				this.SendPropertyChanged("Yg_Pwd");
				this.OnYg_PwdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_XingMing", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_XingMing
	{
		get
		{
			return this._Yg_XingMing;
		}
		set
		{
			if ((this._Yg_XingMing != value))
			{
				this.OnYg_XingMingChanging(value);
				this.SendPropertyChanging();
				this._Yg_XingMing = value;
				this.SendPropertyChanged("Yg_XingMing");
				this.OnYg_XingMingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_MenDian", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_MenDian
	{
		get
		{
			return this._Yg_MenDian;
		}
		set
		{
			if ((this._Yg_MenDian != value))
			{
				this.OnYg_MenDianChanging(value);
				this.SendPropertyChanging();
				this._Yg_MenDian = value;
				this.SendPropertyChanged("Yg_MenDian");
				this.OnYg_MenDianChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_MenDianId", DbType="Int NOT NULL")]
	public int Yg_MenDianId
	{
		get
		{
			return this._Yg_MenDianId;
		}
		set
		{
			if ((this._Yg_MenDianId != value))
			{
				this.OnYg_MenDianIdChanging(value);
				this.SendPropertyChanging();
				this._Yg_MenDianId = value;
				this.SendPropertyChanged("Yg_MenDianId");
				this.OnYg_MenDianIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_XingBie", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
	public string Yg_XingBie
	{
		get
		{
			return this._Yg_XingBie;
		}
		set
		{
			if ((this._Yg_XingBie != value))
			{
				this.OnYg_XingBieChanging(value);
				this.SendPropertyChanging();
				this._Yg_XingBie = value;
				this.SendPropertyChanged("Yg_XingBie");
				this.OnYg_XingBieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_DianHua", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_DianHua
	{
		get
		{
			return this._Yg_DianHua;
		}
		set
		{
			if ((this._Yg_DianHua != value))
			{
				this.OnYg_DianHuaChanging(value);
				this.SendPropertyChanging();
				this._Yg_DianHua = value;
				this.SendPropertyChanged("Yg_DianHua");
				this.OnYg_DianHuaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_ZhuangTai", DbType="Int NOT NULL")]
	public int Yg_ZhuangTai
	{
		get
		{
			return this._Yg_ZhuangTai;
		}
		set
		{
			if ((this._Yg_ZhuangTai != value))
			{
				this.OnYg_ZhuangTaiChanging(value);
				this.SendPropertyChanging();
				this._Yg_ZhuangTai = value;
				this.SendPropertyChanged("Yg_ZhuangTai");
				this.OnYg_ZhuangTaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_JiBie", DbType="Int NOT NULL")]
	public int Yg_JiBie
	{
		get
		{
			return this._Yg_JiBie;
		}
		set
		{
			if ((this._Yg_JiBie != value))
			{
				this.OnYg_JiBieChanging(value);
				this.SendPropertyChanging();
				this._Yg_JiBie = value;
				this.SendPropertyChanged("Yg_JiBie");
				this.OnYg_JiBieChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_ShenFen", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
	public string Yg_ShenFen
	{
		get
		{
			return this._Yg_ShenFen;
		}
		set
		{
			if ((this._Yg_ShenFen != value))
			{
				this.OnYg_ShenFenChanging(value);
				this.SendPropertyChanging();
				this._Yg_ShenFen = value;
				this.SendPropertyChanged("Yg_ShenFen");
				this.OnYg_ShenFenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_XueLi", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Yg_XueLi
	{
		get
		{
			return this._Yg_XueLi;
		}
		set
		{
			if ((this._Yg_XueLi != value))
			{
				this.OnYg_XueLiChanging(value);
				this.SendPropertyChanging();
				this._Yg_XueLi = value;
				this.SendPropertyChanged("Yg_XueLi");
				this.OnYg_XueLiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_NianLing", DbType="Int NOT NULL")]
	public int Yg_NianLing
	{
		get
		{
			return this._Yg_NianLing;
		}
		set
		{
			if ((this._Yg_NianLing != value))
			{
				this.OnYg_NianLingChanging(value);
				this.SendPropertyChanging();
				this._Yg_NianLing = value;
				this.SendPropertyChanged("Yg_NianLing");
				this.OnYg_NianLingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_RuZhi", DbType="Date NOT NULL")]
	public System.DateTime Yg_RuZhi
	{
		get
		{
			return this._Yg_RuZhi;
		}
		set
		{
			if ((this._Yg_RuZhi != value))
			{
				this.OnYg_RuZhiChanging(value);
				this.SendPropertyChanging();
				this._Yg_RuZhi = value;
				this.SendPropertyChanged("Yg_RuZhi");
				this.OnYg_RuZhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_ZhuZhi", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string Yg_ZhuZhi
	{
		get
		{
			return this._Yg_ZhuZhi;
		}
		set
		{
			if ((this._Yg_ZhuZhi != value))
			{
				this.OnYg_ZhuZhiChanging(value);
				this.SendPropertyChanging();
				this._Yg_ZhuZhi = value;
				this.SendPropertyChanged("Yg_ZhuZhi");
				this.OnYg_ZhuZhiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_BeiZhu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Yg_BeiZhu
	{
		get
		{
			return this._Yg_BeiZhu;
		}
		set
		{
			if ((this._Yg_BeiZhu != value))
			{
				this.OnYg_BeiZhuChanging(value);
				this.SendPropertyChanging();
				this._Yg_BeiZhu = value;
				this.SendPropertyChanged("Yg_BeiZhu");
				this.OnYg_BeiZhuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yg_TianJia", DbType="Date NOT NULL")]
	public System.DateTime Yg_TianJia
	{
		get
		{
			return this._Yg_TianJia;
		}
		set
		{
			if ((this._Yg_TianJia != value))
			{
				this.OnYg_TianJiaChanging(value);
				this.SendPropertyChanging();
				this._Yg_TianJia = value;
				this.SendPropertyChanged("Yg_TianJia");
				this.OnYg_TianJiaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
