#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun")]
public partial class linqYeWuDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertYeWu(YeWu instance);
  partial void UpdateYeWu(YeWu instance);
  partial void DeleteYeWu(YeWu instance);
  #endregion
	
	public linqYeWuDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRunConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqYeWuDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYeWuDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYeWuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqYeWuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<YeWu> YeWu
	{
		get
		{
			return this.GetTable<YeWu>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YeWu")]
public partial class YeWu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Yw_Id;
	
	private string _Yw_JingJi;
	
	private int _Yw_JingJiId;
	
	private string _Yw_KeHu;
	
	private int _Yw_KeHuId;
	
	private int _Yw_LeiXing;
	
	private int _Yw_ShangQuan;
	
	private int _Yw_JiaGe;
	
	private int _Yw_MianJi;
	
	private System.DateTime _Yw_YouXiaoQi;
	
	private string _Yw_BeiZhu;
	
	private System.DateTime _Yw_TianJiaShiJian;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYw_IdChanging(int value);
    partial void OnYw_IdChanged();
    partial void OnYw_JingJiChanging(string value);
    partial void OnYw_JingJiChanged();
    partial void OnYw_JingJiIdChanging(int value);
    partial void OnYw_JingJiIdChanged();
    partial void OnYw_KeHuChanging(string value);
    partial void OnYw_KeHuChanged();
    partial void OnYw_KeHuIdChanging(int value);
    partial void OnYw_KeHuIdChanged();
    partial void OnYw_LeiXingChanging(int value);
    partial void OnYw_LeiXingChanged();
    partial void OnYw_ShangQuanChanging(int value);
    partial void OnYw_ShangQuanChanged();
    partial void OnYw_JiaGeChanging(int value);
    partial void OnYw_JiaGeChanged();
    partial void OnYw_MianJiChanging(int value);
    partial void OnYw_MianJiChanged();
    partial void OnYw_YouXiaoQiChanging(System.DateTime value);
    partial void OnYw_YouXiaoQiChanged();
    partial void OnYw_BeiZhuChanging(string value);
    partial void OnYw_BeiZhuChanged();
    partial void OnYw_TianJiaShiJianChanging(System.DateTime value);
    partial void OnYw_TianJiaShiJianChanged();
    #endregion
	
	public YeWu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Yw_Id
	{
		get
		{
			return this._Yw_Id;
		}
		set
		{
			if ((this._Yw_Id != value))
			{
				this.OnYw_IdChanging(value);
				this.SendPropertyChanging();
				this._Yw_Id = value;
				this.SendPropertyChanged("Yw_Id");
				this.OnYw_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_JingJi", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Yw_JingJi
	{
		get
		{
			return this._Yw_JingJi;
		}
		set
		{
			if ((this._Yw_JingJi != value))
			{
				this.OnYw_JingJiChanging(value);
				this.SendPropertyChanging();
				this._Yw_JingJi = value;
				this.SendPropertyChanged("Yw_JingJi");
				this.OnYw_JingJiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_JingJiId", DbType="Int NOT NULL")]
	public int Yw_JingJiId
	{
		get
		{
			return this._Yw_JingJiId;
		}
		set
		{
			if ((this._Yw_JingJiId != value))
			{
				this.OnYw_JingJiIdChanging(value);
				this.SendPropertyChanging();
				this._Yw_JingJiId = value;
				this.SendPropertyChanged("Yw_JingJiId");
				this.OnYw_JingJiIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_KeHu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Yw_KeHu
	{
		get
		{
			return this._Yw_KeHu;
		}
		set
		{
			if ((this._Yw_KeHu != value))
			{
				this.OnYw_KeHuChanging(value);
				this.SendPropertyChanging();
				this._Yw_KeHu = value;
				this.SendPropertyChanged("Yw_KeHu");
				this.OnYw_KeHuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_KeHuId", DbType="Int NOT NULL")]
	public int Yw_KeHuId
	{
		get
		{
			return this._Yw_KeHuId;
		}
		set
		{
			if ((this._Yw_KeHuId != value))
			{
				this.OnYw_KeHuIdChanging(value);
				this.SendPropertyChanging();
				this._Yw_KeHuId = value;
				this.SendPropertyChanged("Yw_KeHuId");
				this.OnYw_KeHuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_LeiXing", DbType="Int NOT NULL")]
	public int Yw_LeiXing
	{
		get
		{
			return this._Yw_LeiXing;
		}
		set
		{
			if ((this._Yw_LeiXing != value))
			{
				this.OnYw_LeiXingChanging(value);
				this.SendPropertyChanging();
				this._Yw_LeiXing = value;
				this.SendPropertyChanged("Yw_LeiXing");
				this.OnYw_LeiXingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_ShangQuan", DbType="Int NOT NULL")]
	public int Yw_ShangQuan
	{
		get
		{
			return this._Yw_ShangQuan;
		}
		set
		{
			if ((this._Yw_ShangQuan != value))
			{
				this.OnYw_ShangQuanChanging(value);
				this.SendPropertyChanging();
				this._Yw_ShangQuan = value;
				this.SendPropertyChanged("Yw_ShangQuan");
				this.OnYw_ShangQuanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_JiaGe", DbType="Int NOT NULL")]
	public int Yw_JiaGe
	{
		get
		{
			return this._Yw_JiaGe;
		}
		set
		{
			if ((this._Yw_JiaGe != value))
			{
				this.OnYw_JiaGeChanging(value);
				this.SendPropertyChanging();
				this._Yw_JiaGe = value;
				this.SendPropertyChanged("Yw_JiaGe");
				this.OnYw_JiaGeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_MianJi", DbType="Int NOT NULL")]
	public int Yw_MianJi
	{
		get
		{
			return this._Yw_MianJi;
		}
		set
		{
			if ((this._Yw_MianJi != value))
			{
				this.OnYw_MianJiChanging(value);
				this.SendPropertyChanging();
				this._Yw_MianJi = value;
				this.SendPropertyChanged("Yw_MianJi");
				this.OnYw_MianJiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_YouXiaoQi", DbType="SmallDateTime NOT NULL")]
	public System.DateTime Yw_YouXiaoQi
	{
		get
		{
			return this._Yw_YouXiaoQi;
		}
		set
		{
			if ((this._Yw_YouXiaoQi != value))
			{
				this.OnYw_YouXiaoQiChanging(value);
				this.SendPropertyChanging();
				this._Yw_YouXiaoQi = value;
				this.SendPropertyChanged("Yw_YouXiaoQi");
				this.OnYw_YouXiaoQiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_BeiZhu", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Yw_BeiZhu
	{
		get
		{
			return this._Yw_BeiZhu;
		}
		set
		{
			if ((this._Yw_BeiZhu != value))
			{
				this.OnYw_BeiZhuChanging(value);
				this.SendPropertyChanging();
				this._Yw_BeiZhu = value;
				this.SendPropertyChanged("Yw_BeiZhu");
				this.OnYw_BeiZhuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yw_TianJiaShiJian", DbType="SmallDateTime NOT NULL")]
	public System.DateTime Yw_TianJiaShiJian
	{
		get
		{
			return this._Yw_TianJiaShiJian;
		}
		set
		{
			if ((this._Yw_TianJiaShiJian != value))
			{
				this.OnYw_TianJiaShiJianChanging(value);
				this.SendPropertyChanging();
				this._Yw_TianJiaShiJian = value;
				this.SendPropertyChanged("Yw_TianJiaShiJian");
				this.OnYw_TianJiaShiJianChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
