#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HeRun2")]
public partial class linqFangYuanDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertFangYuan(FangYuan instance);
  partial void UpdateFangYuan(FangYuan instance);
  partial void DeleteFangYuan(FangYuan instance);
  #endregion
	
	public linqFangYuanDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HeRun2ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public linqFangYuanDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqFangYuanDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqFangYuanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public linqFangYuanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<FangYuan> FangYuan
	{
		get
		{
			return this.GetTable<FangYuan>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FangYuan")]
public partial class FangYuan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _FY_Id;
	
	private int _Fy_KeHuId;
	
	private int _Fy_YuanGongId;
	
	private int _Fy_ZhuangTai;
	
	private int _Fy_ChengQu;
	
	private int _Fy_ShangQuan;
	
	private string _Fy_Gmaps;
	
	private int _Fy_JiaGe;
	
	private int _Fy_MianJi;
	
	private string _Fy_JiaJu;
	
	private string _Fy_ShangChao;
	
	private string _Fy_JiaoTong;
	
	private string _Fy_XiangXi;
	
	private System.DateTime _Fy_TianJiaRiQi;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFY_IdChanging(int value);
    partial void OnFY_IdChanged();
    partial void OnFy_KeHuIdChanging(int value);
    partial void OnFy_KeHuIdChanged();
    partial void OnFy_YuanGongIdChanging(int value);
    partial void OnFy_YuanGongIdChanged();
    partial void OnFy_ZhuangTaiChanging(int value);
    partial void OnFy_ZhuangTaiChanged();
    partial void OnFy_ChengQuChanging(int value);
    partial void OnFy_ChengQuChanged();
    partial void OnFy_ShangQuanChanging(int value);
    partial void OnFy_ShangQuanChanged();
    partial void OnFy_GmapsChanging(string value);
    partial void OnFy_GmapsChanged();
    partial void OnFy_JiaGeChanging(int value);
    partial void OnFy_JiaGeChanged();
    partial void OnFy_MianJiChanging(int value);
    partial void OnFy_MianJiChanged();
    partial void OnFy_JiaJuChanging(string value);
    partial void OnFy_JiaJuChanged();
    partial void OnFy_ShangChaoChanging(string value);
    partial void OnFy_ShangChaoChanged();
    partial void OnFy_JiaoTongChanging(string value);
    partial void OnFy_JiaoTongChanged();
    partial void OnFy_XiangXiChanging(string value);
    partial void OnFy_XiangXiChanged();
    partial void OnFy_TianJiaRiQiChanging(System.DateTime value);
    partial void OnFy_TianJiaRiQiChanged();
    #endregion
	
	public FangYuan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FY_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int FY_Id
	{
		get
		{
			return this._FY_Id;
		}
		set
		{
			if ((this._FY_Id != value))
			{
				this.OnFY_IdChanging(value);
				this.SendPropertyChanging();
				this._FY_Id = value;
				this.SendPropertyChanged("FY_Id");
				this.OnFY_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_KeHuId", DbType="Int NOT NULL")]
	public int Fy_KeHuId
	{
		get
		{
			return this._Fy_KeHuId;
		}
		set
		{
			if ((this._Fy_KeHuId != value))
			{
				this.OnFy_KeHuIdChanging(value);
				this.SendPropertyChanging();
				this._Fy_KeHuId = value;
				this.SendPropertyChanged("Fy_KeHuId");
				this.OnFy_KeHuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_YuanGongId", DbType="Int NOT NULL")]
	public int Fy_YuanGongId
	{
		get
		{
			return this._Fy_YuanGongId;
		}
		set
		{
			if ((this._Fy_YuanGongId != value))
			{
				this.OnFy_YuanGongIdChanging(value);
				this.SendPropertyChanging();
				this._Fy_YuanGongId = value;
				this.SendPropertyChanged("Fy_YuanGongId");
				this.OnFy_YuanGongIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_ZhuangTai", DbType="Int NOT NULL")]
	public int Fy_ZhuangTai
	{
		get
		{
			return this._Fy_ZhuangTai;
		}
		set
		{
			if ((this._Fy_ZhuangTai != value))
			{
				this.OnFy_ZhuangTaiChanging(value);
				this.SendPropertyChanging();
				this._Fy_ZhuangTai = value;
				this.SendPropertyChanged("Fy_ZhuangTai");
				this.OnFy_ZhuangTaiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_ChengQu", DbType="Int NOT NULL")]
	public int Fy_ChengQu
	{
		get
		{
			return this._Fy_ChengQu;
		}
		set
		{
			if ((this._Fy_ChengQu != value))
			{
				this.OnFy_ChengQuChanging(value);
				this.SendPropertyChanging();
				this._Fy_ChengQu = value;
				this.SendPropertyChanged("Fy_ChengQu");
				this.OnFy_ChengQuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_ShangQuan", DbType="Int NOT NULL")]
	public int Fy_ShangQuan
	{
		get
		{
			return this._Fy_ShangQuan;
		}
		set
		{
			if ((this._Fy_ShangQuan != value))
			{
				this.OnFy_ShangQuanChanging(value);
				this.SendPropertyChanging();
				this._Fy_ShangQuan = value;
				this.SendPropertyChanged("Fy_ShangQuan");
				this.OnFy_ShangQuanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_Gmaps", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Fy_Gmaps
	{
		get
		{
			return this._Fy_Gmaps;
		}
		set
		{
			if ((this._Fy_Gmaps != value))
			{
				this.OnFy_GmapsChanging(value);
				this.SendPropertyChanging();
				this._Fy_Gmaps = value;
				this.SendPropertyChanged("Fy_Gmaps");
				this.OnFy_GmapsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_JiaGe", DbType="Int NOT NULL")]
	public int Fy_JiaGe
	{
		get
		{
			return this._Fy_JiaGe;
		}
		set
		{
			if ((this._Fy_JiaGe != value))
			{
				this.OnFy_JiaGeChanging(value);
				this.SendPropertyChanging();
				this._Fy_JiaGe = value;
				this.SendPropertyChanged("Fy_JiaGe");
				this.OnFy_JiaGeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_MianJi", DbType="Int NOT NULL")]
	public int Fy_MianJi
	{
		get
		{
			return this._Fy_MianJi;
		}
		set
		{
			if ((this._Fy_MianJi != value))
			{
				this.OnFy_MianJiChanging(value);
				this.SendPropertyChanging();
				this._Fy_MianJi = value;
				this.SendPropertyChanged("Fy_MianJi");
				this.OnFy_MianJiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_JiaJu", DbType="VarChar(50)")]
	public string Fy_JiaJu
	{
		get
		{
			return this._Fy_JiaJu;
		}
		set
		{
			if ((this._Fy_JiaJu != value))
			{
				this.OnFy_JiaJuChanging(value);
				this.SendPropertyChanging();
				this._Fy_JiaJu = value;
				this.SendPropertyChanged("Fy_JiaJu");
				this.OnFy_JiaJuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_ShangChao", DbType="VarChar(50)")]
	public string Fy_ShangChao
	{
		get
		{
			return this._Fy_ShangChao;
		}
		set
		{
			if ((this._Fy_ShangChao != value))
			{
				this.OnFy_ShangChaoChanging(value);
				this.SendPropertyChanging();
				this._Fy_ShangChao = value;
				this.SendPropertyChanged("Fy_ShangChao");
				this.OnFy_ShangChaoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_JiaoTong", DbType="VarChar(50)")]
	public string Fy_JiaoTong
	{
		get
		{
			return this._Fy_JiaoTong;
		}
		set
		{
			if ((this._Fy_JiaoTong != value))
			{
				this.OnFy_JiaoTongChanging(value);
				this.SendPropertyChanging();
				this._Fy_JiaoTong = value;
				this.SendPropertyChanged("Fy_JiaoTong");
				this.OnFy_JiaoTongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_XiangXi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Fy_XiangXi
	{
		get
		{
			return this._Fy_XiangXi;
		}
		set
		{
			if ((this._Fy_XiangXi != value))
			{
				this.OnFy_XiangXiChanging(value);
				this.SendPropertyChanging();
				this._Fy_XiangXi = value;
				this.SendPropertyChanged("Fy_XiangXi");
				this.OnFy_XiangXiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fy_TianJiaRiQi", DbType="Date NOT NULL")]
	public System.DateTime Fy_TianJiaRiQi
	{
		get
		{
			return this._Fy_TianJiaRiQi;
		}
		set
		{
			if ((this._Fy_TianJiaRiQi != value))
			{
				this.OnFy_TianJiaRiQiChanging(value);
				this.SendPropertyChanging();
				this._Fy_TianJiaRiQi = value;
				this.SendPropertyChanged("Fy_TianJiaRiQi");
				this.OnFy_TianJiaRiQiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
